#!/usr/bin/env bash
# Script to audit DNS records


get_subdomain_info () {
    argument=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $argument" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
    for subdomain in "www" "lb-01" "web-01" "web-02"
    do
        get_subdomain_info "$1" "$subdomain"
    done
elif [ "$#" == 2 ]
then
    get_subdomain_info "$1" "$2"
fi
