#!/usr/bin/env bash
# This script transfers a file from our client to a server

if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

PathFile=$1
IpServer=$2
UserName=$3
PathToSshkey=$4

scp -o StrictHostKeyChecking=no -i "$PathToSshkey" "$PathFile" "$UserName@$IpServer:~/"

