#!/usr/bin/env bash
# install web_server nginx

sudo apt-get update
sudo apt-get install nginx
sudo ufw "Nginx HTTP"
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo nginx -t
sudo service nginx reload
