#!/usr/bin/env bash
# Install web server nginx

# Update package list
sudo apt-get update -y

# Install nginx
sudo apt-get install -y nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a simple HTML file
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo service nginx reload
