#!/usr/bin/env bash
# Install web server nginx

sudo apt-get update -y

sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html

sudo nginx -t
sudo service nginx reload

