#!/usr/bin/env bash
# install HAProxy load balancer for two web servers

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install haproxy

config="\nlisten load-balancer
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 46996-web-01 35.174.205.23:80 check
	server 46996-web-02 52.91.178.16:80 check"

echo -e "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
