#!/usr/bin/env bash
# Set up and configure HAProxy on your lb-01 server

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy=1.8.\*

lb="\nfrontend http\n
\tbind *:80
\tmode http
\tdefault_backend load_b

backend load_b\n
\tbalance roundrobin
\tserver web-01 35.174.205.23 check
\tserver web-02 52.91.178.16 check
"
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy
echo -e "$lb" | sudo tee -a /etc/haproxy/haproxy.cfg

service haproxy restart
