#!/bin/bash

# Update package lists
sudo apt-get update

# Install haproxy
sudo apt-get install -y haproxy

# Enable haproxy
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Create and configure haproxy.cfg
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
frontend http
    bind *:80
    mode http
    default_backend load_b

backend load_b
    balance roundrobin
    server web-01 35.174.205.23 check
    server web-02 52.91.178.16 check
EOL

# Enable and start haproxy service
sudo systemctl enable haproxy
sudo systemctl start haproxy

# Check haproxy status
sudo systemctl status haproxy
