#!/usr/bin/env bash
# Set up Nginx server to listen on port 80 as previously configured
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
pkill nginx
nginx
