#!/bin/bash
# this script for  handle SIGTERM and SIGQUIT signals

HandelTerm() {
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit
}

handelSigint() {
    echo "Y U no love me?!"
}

trap 'sigterm_sigquit_handler' SIGTERM SIGQUIT
trap 'sigint_handler' SIGINT
echo "$$" > /var/run/myscript.pid
while true; do
    echo "To infinity and beyond"
    sleep 2
done
