#!/usr/bin/env bash
# this scropt for desplay "Best school" ten times

a=0

while [ $a -lt 10 ]
do
        if [ $a -eq 9 ]
        then
                echo "Hi"
        fi
        echo "Best school"
        ((a++))
done
