#!/usr/bin/env bash
# this scropt for desplay "Best school" ten times, if 9th desplay 'Hi'

C=0
while [ $C -lt 11 ]
do
    if [ $C = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((C++))
done
