#!/user/bin/env bash
# setup a few rules on web-01 & install ufw

sudo apt install -y ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22
sudo allow 443
sudo ufw allow 80
echo "y" | sudo ufw enable
