#!/usr/bin/env bash
# this script for edit hostfile
# change localhost & facebook adresses
sudo cp /etc/hosts ~/hosts.new
sudo sed -i 's/^127.0.0.1.*localhost$/127.0.0.2    localhost/' /etc/hosts
sudo sed -i 's/^.*facebook.com$/8.8.8.8    facebook.com/' /etc/hosts
cp -f ~/hosts.new /etc/hosts
