#!/usr/bin/env bash
# this script for edit hostfile
# change localhost & facebook adresses
cp /etc/hosts ~/hosts.new
sudo sed -i 's/^127.0.0.1.*localhost$/127.0.0.2    localhost/' ~/hosts.new
sudo sed -i 's/^.*facebook.com$/8.8.8.8    facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
